### ISSUE TITLE
Request: disable the logging of Ping times

### ISSUE THREAD

**Issue by Ubimo** [Ranger802004/asusmerlin#65]
Thanks for your work.
Could you kindly consider implementing an option to disable the logging of Ping times in the syslog?

**Comment by Ranger802004** [comment]
This will be available in the next beta release coming soon.

**Comment by Ranger802004** [comment]
***v2.2.0-beta1 has been released to the beta update channel***

v2.2.0-beta1 - 03/26/2025
Enhancements:
- Support for 3006 Codebase
- Added PINGTIMELOGGING configuration option, this option allows ping time logging to be enabled or disabled. Default: Enabled
- Added new Dev Mode to support disabling update channels.

Fixes:
- Fixed an issue where WGSERVERS parameter was causing script to hang during failover events.
- Resolved an issue where RECURSIVEPINGCHECK loop would prevent WAN restart actions to occur.  
	- Credit for identifying issue: https://github.com/Tigger2014 & https://github.com/nathan57971
- Removed use of pstree to detect and kill PIDs for WAN Failover due to inconsistencies with use.

Known Issues:
- LED service is not restarted in 3006 Codebase during WAN Failover events.

**Comment by Ubimo** [comment]
Although I disabled ping time logging, I still see the entries in syslog:

![Image](https://github.com/user-attachments/assets/50f52891-6b16-4db0-8e8d-6771a13ab131)
![Image](https://github.com/user-attachments/assets/04f23fe9-63f6-49b7-ab09-aa0d0cd4cc61)

**Comment by Ubimo** [comment]
Just FYI, tonight, I had a brief connection outage of WAN0. The script successfully switched to WAN1 and then back to WAN0.
Since then, there is no more logging of ping times in syslog.

**Comment by Ranger802004** [comment]
Did you let WAN failover restart after changing the configuration? The configuration menu should have gave a warning about needing to do this for this setting.

**Comment by Ranger802004** [comment]
Excellent news.  This will be included in the final release of this version of WAN Failover.
