### ISSUE TITLE
Domain Routing over vpn for some reason does not function after updating to 3006.x version on an AXE16000

### ISSUE THREAD

**Issue by Jerkysan** [Ranger802004/asusmerlin#78]
So this was working flawlessly on the 3004 version and I kind of feel bad putting an issue in for it since 3006 is beta software. Anyways if you don't want to work it then just tell me..

After upgrading to 3006 domain routing stopped. This was all tried on latest beta of domain_vpn_routing and the latest GA

I tried uninstalling/reinstalling that didn't fix it.(restored configuration during install)

I tried uninstalling/reinstalling without restoring backup and setting all policies up from scratch.

I uninstalled then deleted the client vpn and set it all up from scratch again. Still fails to route.

I'm unsure where to even look for what is occurring.

Testing was using both cmd/tracert and attempting to go to certain sites that show your IP address you are originating from. Any suggestions would be great.

**Comment by Jerkysan** [comment]
So I saw the other issue about the domain IP's being empty and mine was as well... so I downgraded to 3.0.6.. queried everything but then the null route thing broke it, so then I upgraded back to beta2 and now it does route over the vpn but my guess it will break when the ips change but at least nice I can kind of get it working. Do I need to close this because it's basically what the other user stated about the IP's not being actually updated. I am not using dns over tls or anything special.

**Comment by Ranger802004** [comment]
Don't feel bad for submitting an issue, it is something I would like to resolve and allow the Domain VPN Routing to work on the new codebase.  I will come up with some test scenarios and get back with you to perform those tests and report back.

**Comment by Ranger802004** [comment]
Try this new beta, review your domain IP lists and make sure your DNS servers weren't erroneously added to a policy.  If they were use the deleteip function from the UI menu to remove them from all policies.

Release Notes:
v3.1.1-beta3 - 04/23/2025
Enhancements:
- If DNS-over-TLS is enabled and servers are configured on the system DNS-over-TLS DNS server list, dig will configure use for DNS-over-TLS by randomly selecting a DNS-over-TLS DNS server.  
	- Python3 and dig are required to be installed for this functionality.
	- An existing DNS configuration for the interface in Domain VPN Routing will override this functionality.
- Added debug logging for DNS-over-TLS configuration during querypolicy function execution.

Fixes:
- Fixed an issue with IPv4 unreachable rules being created for VPN interfaces due to a missing default route for the VPN routing table.
- Fixed an issue where restoreasncache was executing when restoring an individual policy, this will still execute when restoring all policies.
- Fixes issues with erroneous data being ingested by dig.
- Minor fixes and optimizations

**Comment by Jerkysan** [comment]
I verified that my dns isn't in there.(I even switched back to my ISPs dns).  But no the beta3 did not fix the issue of it not updating the IPs in the list.

**Comment by Ranger802004** [comment]
What if you install 3.0.6 on 3006 code base?

**Comment by Jerkysan** [comment]
Yes that resolves it. That is actually how I'm still working because I downgraded to version 3.0.6 did the domain query and then upgraded again.

**Comment by Ranger802004** [comment]
Can you enable debug logging on your router and run the latest beta version going through your test plan and provide the logs? Thanks

**Comment by Ranger802004** [comment]
Did that capture IPv6 addresses?

**Comment by Jerkysan** [comment]
I don't have IPV6 but no it didn't capture it or ipv4

**Comment by Jerkysan** [comment]
create DVR-Test-v6 hash:ip family inet6 hashsize 1024 maxelem 65536 comment
~
~
~
create DVR-Test-v4 hash:ip family inet hashsize 1024 maxelem 65536 comment
~
~
~
~
~
~
This is what is inside the files

**Comment by Ranger802004** [comment]
Can you provide an output of the full debug logs?

**Comment by Jerkysan** [comment]
Sorry is this what your after? 

Apr 23 14:03:49 domain_vpn_routing: Create Policy - Creating /jffs/configs/domain_vpn_routing/policy_Test_domainlist
Apr 23 14:03:49 domain_vpn_routing: Create Policy - /jffs/configs/domain_vpn_routing/policy_Test_domainlist created
Apr 23 14:03:49 domain_vpn_routing: Create Policy - Creating /jffs/configs/domain_vpn_routing/policy_Test_domaintoIP
Apr 23 14:03:49 domain_vpn_routing: Create Policy - /jffs/configs/domain_vpn_routing/policy_Test_domaintoIP created
Apr 23 14:03:49 domain_vpn_routing: Create Policy - Adding Test to /jffs/configs/domain_vpn_routing/domain_vpn_routing.conf
Apr 23 14:03:49 domain_vpn_routing: Create Policy - Added Test to /jffs/configs/domain_vpn_routing/domain_vpn_routing.conf
Apr 23 14:03:51 domain_vpn_routing: Debug - DNSLOGGINGENABLED: 0
Apr 23 14:03:51 domain_vpn_routing: Debug - DNSLOGPATH: 
Apr 23 14:03:51 domain_vpn_routing: Debug - Entware is installed
Apr 23 14:03:51 domain_vpn_routing: Debug - Entware is mounted to /opt/bin
Apr 23 14:03:51 domain_vpn_routing: Debug - ENTWAREINSTALLED: 1
Apr 23 14:03:51 domain_vpn_routing: Debug - ENTWAREMOUNTED: 1
Apr 23 14:03:51 domain_vpn_routing: Debug - DIGINSTALLED: 1
Apr 23 14:03:51 domain_vpn_routing: Debug - JQINSTALLED: 0
Apr 23 14:03:51 domain_vpn_routing: Debug - PYTHON3INSTALLED: 0
Apr 23 14:03:51 domain_vpn_routing: Debug - ADGUARDHOMEACTIVE: 0
Apr 23 14:03:51 domain_vpn_routing: Debug - ADGUARDHOMELOGENABLED: 0
Apr 23 14:03:51 domain_vpn_routing: Debug - DOTDNSSERVERS: 
Apr 23 14:03:51 domain_vpn_routing: Debug - Reading /jffs/configs/domain_vpn_routing/global.conf
Apr 23 14:04:01 domain_vpn_routing: Add Domain - Adding www.cnbc.com to Test
Apr 23 14:04:01 domain_vpn_routing: Add Domain - Added www.cnbc.com to Test
Apr 23 14:04:02 domain_vpn_routing: Debug - DNSLOGGINGENABLED: 0
Apr 23 14:04:02 domain_vpn_routing: Debug - DNSLOGPATH: 
Apr 23 14:04:02 domain_vpn_routing: Debug - Entware is installed
Apr 23 14:04:02 domain_vpn_routing: Debug - Entware is mounted to /opt/bin
Apr 23 14:04:02 domain_vpn_routing: Debug - ENTWAREINSTALLED: 1
Apr 23 14:04:02 domain_vpn_routing: Debug - ENTWAREMOUNTED: 1
Apr 23 14:04:02 domain_vpn_routing: Debug - DIGINSTALLED: 1
Apr 23 14:04:02 domain_vpn_routing: Debug - JQINSTALLED: 0
Apr 23 14:04:02 domain_vpn_routing: Debug - PYTHON3INSTALLED: 0
Apr 23 14:04:02 domain_vpn_routing: Debug - ADGUARDHOMEACTIVE: 0
Apr 23 14:04:02 domain_vpn_routing: Debug - ADGUARDHOMELOGENABLED: 0
Apr 23 14:04:02 domain_vpn_routing: Debug - DOTDNSSERVERS: 
Apr 23 14:04:02 domain_vpn_routing: Debug - Reading /jffs/configs/domain_vpn_routing/global.conf
Apr 23 14:04:07 domain_vpn_routing: Debug - Domain VPN Routing is Enabled
Apr 23 14:04:07 domain_vpn_routing: Debug - Checking Alias in /jffs/configs/profile.add
Apr 23 14:04:07 domain_vpn_routing: Debug - Setting Process Priority to 0
Apr 23 14:04:07 domain_vpn_routing: Set Process Priority - Set Process Priority to 0
Apr 23 14:04:07 domain_vpn_routing: Debug - Domain VPN Routing is Enabled
Apr 23 14:04:07 domain_vpn_routing: Debug - Setting Process Priority to 0
Apr 23 14:04:07 domain_vpn_routing: Set Process Priority - Set Process Priority to 0
Apr 23 14:04:07 domain_vpn_routing: Debug - Routing Director Interface: wgc2
Apr 23 14:04:07 domain_vpn_routing: Debug - State: 1
Apr 23 14:04:07 domain_vpn_routing: Restore Policy - Creating IPv6 IPSET for Test
Apr 23 14:04:07 domain_vpn_routing: Restore Policy - Created IPv6 IPSET for Test
Apr 23 14:04:07 domain_vpn_routing: Restore Policy - Creating IPv4 IPSET for Test
Apr 23 14:04:07 domain_vpn_routing: Restore Policy - Created IPv4 IPSET for Test
Apr 23 14:04:07 domain_vpn_routing: Restore Policy - Adding IPTables OUTPUT rule for IPSET: DVR-Test-v4 FWMark: 0xb000
Apr 23 14:04:07 domain_vpn_routing: Restore Policy - Added IPTables OUTPUT rule for IPSET: DVR-Test-v4 FWMark: 0xb000
Apr 23 14:04:07 domain_vpn_routing: Restore Policy - Adding IPTables PREROUTING rule for IPSET: DVR-Test-v4 FWMark: 0xb000
Apr 23 14:04:07 domain_vpn_routing: Restore Policy - Added IPTables PREROUTING rule for IPSET: DVR-Test-v4 FWMark: 0xb000
Apr 23 14:04:07 domain_vpn_routing: Restore Policy - Adding IPTables rule for IPSET: DVR-Test-v4 Interface: wgc2 FWMark: 0xb000
Apr 23 14:04:07 domain_vpn_routing: Restore Policy - Added IPTables rule for IPSET: DVR-Test-v4 Interface: wgc2 FWMark: 0xb000
Apr 23 14:04:07 domain_vpn_routing: Restore Policy - Saving IPv4 IPSET for Test
Apr 23 14:04:07 domain_vpn_routing: Restore Policy - Save IPv4 IPSET for Test
Apr 23 14:04:07 domain_vpn_routing: Debug - DNS Director Interface: wgc2
Apr 23 14:04:07 domain_vpn_routing: Debug - Dig has been configured to use system DNS Server
Apr 23 14:04:07 domain_vpn_routing: Debug - Dig has been configured without DNS-over-TLS using DNS Server: 
Apr 23 14:04:07 domain_vpn_routing: Query Policy - Policy: Test Querying www.cnbc.com
Apr 23 14:04:07 domain_vpn_routing: Debug - Routing Director Interface: wgc2
Apr 23 14:04:07 domain_vpn_routing: Debug - State: 1
Apr 23 14:04:07 domain_vpn_routing: Query Policy - Saving IPv6 IPSET for Test
Apr 23 14:04:07 domain_vpn_routing: Query Policy - Saved IPv6 IPSET for Test
Apr 23 14:04:07 domain_vpn_routing: Query Policy - Processing Time: 0 seconds
Apr 23 14:04:07 domain_vpn_routing: Debug - Checking for Lock File: /var/lock/domain_vpn_routing.lock
Apr 23 14:04:07 domain_vpn_routing: Cleanup - Deleting /var/lock/domain_vpn_routing.lock
Apr 23 14:04:07 domain_vpn_routing: Cleanup - Deleted /var/lock/domain_vpn_routing.lock
Apr 23 14:04:09 domain_vpn_routing: Debug - DNSLOGGINGENABLED: 0
Apr 23 14:04:09 domain_vpn_routing: Debug - DNSLOGPATH: 
Apr 23 14:04:09 domain_vpn_routing: Debug - Entware is installed
Apr 23 14:04:09 domain_vpn_routing: Debug - Entware is mounted to /opt/bin
Apr 23 14:04:09 domain_vpn_routing: Debug - ENTWAREINSTALLED: 1
Apr 23 14:04:09 domain_vpn_routing: Debug - ENTWAREMOUNTED: 1
Apr 23 14:04:09 domain_vpn_routing: Debug - DIGINSTALLED: 1
Apr 23 14:04:09 domain_vpn_routing: Debug - JQINSTALLED: 0
Apr 23 14:04:09 domain_vpn_routing: Debug - PYTHON3INSTALLED: 0
Apr 23 14:04:10 domain_vpn_routing: Debug - ADGUARDHOMEACTIVE: 0
Apr 23 14:04:10 domain_vpn_routing: Debug - ADGUARDHOMELOGENABLED: 0
Apr 23 14:04:10 domain_vpn_routing: Debug - DOTDNSSERVERS: 
Apr 23 14:04:10 domain_vpn_routing: Debug - Reading /jffs/configs/domain_vpn_routing/global.conf

**Comment by Ranger802004** [comment]
Ok I believe I have identified the issue and will publish a fix to the beta channel soon.

**Comment by Ranger802004** [comment]
Test with new beta release.

Release Notes:
v3.1.1-beta4 - 04/23/2025
Enhancements:
- If DNS-over-TLS is enabled and servers are configured on the system DNS-over-TLS DNS server list, dig will configure use for DNS-over-TLS by randomly selecting a DNS-over-TLS DNS server.  
	- Python3 and dig are required to be installed for this functionality.
	- An existing DNS configuration for the interface in Domain VPN Routing will override this functionality.
- Added debug logging for DNS-over-TLS configuration during querypolicy function execution.

Fixes:
- Fixed an issue with IPv4 unreachable rules being created for VPN interfaces due to a missing default route for the VPN routing table.
- Fixed an issue where restoreasncache was executing when restoring an individual policy, this will still execute when restoring all policies.
- Fixed issues with erroneous data being ingested by dig.
- Fixed an issue with dig applying DNS Server configuration incorrectly and causing unreturned data from queries.
- Minor fixes and optimizations

**Comment by Jerkysan** [comment]
Select the Policy You Want to Query: 4
Query Policy: Test
domain_vpn_routing: Query Policy - Policy: Test Querying www.cnbc.com
domain_vpn_routing: Query Policy - Policy: Test Querying www.cnbc.com.edgekey.net
***New IP Addresses detected for Test***
Updating Policy: Test
Updated Policy: Test
domain_vpn_routing: Query Policy - Processing Time: 1 seconds

**Comment by Jerkysan** [comment]
Let me get the debug because it says it found Ips but it didn't actually do anything. Standby

**Comment by Jerkysan** [comment]
Apr 23 14:36:15 domain_vpn_routing: Create Policy - Creating /jffs/configs/domain_vpn_routing/policy_Test_domainlist
Apr 23 14:36:15 domain_vpn_routing: Create Policy - /jffs/configs/domain_vpn_routing/policy_Test_domainlist created
Apr 23 14:36:15 domain_vpn_routing: Create Policy - Creating /jffs/configs/domain_vpn_routing/policy_Test_domaintoIP
Apr 23 14:36:15 domain_vpn_routing: Create Policy - /jffs/configs/domain_vpn_routing/policy_Test_domaintoIP created
Apr 23 14:36:15 domain_vpn_routing: Create Policy - Adding Test to /jffs/configs/domain_vpn_routing/domain_vpn_routing.conf
Apr 23 14:36:15 domain_vpn_routing: Create Policy - Added Test to /jffs/configs/domain_vpn_routing/domain_vpn_routing.conf
Apr 23 14:36:16 domain_vpn_routing: Debug - DNSLOGGINGENABLED: 0
Apr 23 14:36:16 domain_vpn_routing: Debug - DNSLOGPATH: 
Apr 23 14:36:16 domain_vpn_routing: Debug - Entware is installed
Apr 23 14:36:16 domain_vpn_routing: Debug - Entware is mounted to /opt/bin
Apr 23 14:36:16 domain_vpn_routing: Debug - ENTWAREINSTALLED: 1
Apr 23 14:36:16 domain_vpn_routing: Debug - ENTWAREMOUNTED: 1
Apr 23 14:36:16 domain_vpn_routing: Debug - DIGINSTALLED: 1
Apr 23 14:36:16 domain_vpn_routing: Debug - JQINSTALLED: 0
Apr 23 14:36:16 domain_vpn_routing: Debug - PYTHON3INSTALLED: 0
Apr 23 14:36:16 domain_vpn_routing: Debug - ADGUARDHOMEACTIVE: 0
Apr 23 14:36:16 domain_vpn_routing: Debug - ADGUARDHOMELOGENABLED: 0
Apr 23 14:36:16 domain_vpn_routing: Debug - DOTDNSSERVERS: 
Apr 23 14:36:16 domain_vpn_routing: Debug - Reading /jffs/configs/domain_vpn_routing/global.conf
Apr 23 14:36:25 domain_vpn_routing: Add Domain - Adding www.cnbc.com to Test
Apr 23 14:36:25 domain_vpn_routing: Add Domain - Added www.cnbc.com to Test
Apr 23 14:36:26 domain_vpn_routing: Debug - DNSLOGGINGENABLED: 0
Apr 23 14:36:26 domain_vpn_routing: Debug - DNSLOGPATH: 
Apr 23 14:36:26 domain_vpn_routing: Debug - Entware is installed
Apr 23 14:36:26 domain_vpn_routing: Debug - Entware is mounted to /opt/bin
Apr 23 14:36:26 domain_vpn_routing: Debug - ENTWAREINSTALLED: 1
Apr 23 14:36:26 domain_vpn_routing: Debug - ENTWAREMOUNTED: 1
Apr 23 14:36:26 domain_vpn_routing: Debug - DIGINSTALLED: 1
Apr 23 14:36:26 domain_vpn_routing: Debug - JQINSTALLED: 0
Apr 23 14:36:26 domain_vpn_routing: Debug - PYTHON3INSTALLED: 0
Apr 23 14:36:26 domain_vpn_routing: Debug - ADGUARDHOMEACTIVE: 0
Apr 23 14:36:26 domain_vpn_routing: Debug - ADGUARDHOMELOGENABLED: 0
Apr 23 14:36:26 domain_vpn_routing: Debug - DOTDNSSERVERS: 
Apr 23 14:36:26 domain_vpn_routing: Debug - Reading /jffs/configs/domain_vpn_routing/global.conf
Apr 23 14:36:31 domain_vpn_routing: Debug - Domain VPN Routing is Enabled
Apr 23 14:36:31 domain_vpn_routing: Debug - Checking Alias in /jffs/configs/profile.add
Apr 23 14:36:31 domain_vpn_routing: Debug - Setting Process Priority to 0
Apr 23 14:36:31 domain_vpn_routing: Set Process Priority - Set Process Priority to 0
Apr 23 14:36:31 domain_vpn_routing: Debug - Domain VPN Routing is Enabled
Apr 23 14:36:31 domain_vpn_routing: Debug - Setting Process Priority to 0
Apr 23 14:36:31 domain_vpn_routing: Set Process Priority - Set Process Priority to 0
Apr 23 14:36:31 domain_vpn_routing: Debug - Routing Director Interface: wgc2
Apr 23 14:36:31 domain_vpn_routing: Debug - State: 1
Apr 23 14:36:31 domain_vpn_routing: Restore Policy - Creating IPv6 IPSET for Test
Apr 23 14:36:31 domain_vpn_routing: Restore Policy - Created IPv6 IPSET for Test
Apr 23 14:36:31 domain_vpn_routing: Restore Policy - Creating IPv4 IPSET for Test
Apr 23 14:36:31 domain_vpn_routing: Restore Policy - Created IPv4 IPSET for Test
Apr 23 14:36:31 domain_vpn_routing: Restore Policy - Adding IPTables OUTPUT rule for IPSET: DVR-Test-v4 FWMark: 0xb000
Apr 23 14:36:31 domain_vpn_routing: Restore Policy - Added IPTables OUTPUT rule for IPSET: DVR-Test-v4 FWMark: 0xb000
Apr 23 14:36:31 domain_vpn_routing: Restore Policy - Adding IPTables PREROUTING rule for IPSET: DVR-Test-v4 FWMark: 0xb000
Apr 23 14:36:31 domain_vpn_routing: Restore Policy - Added IPTables PREROUTING rule for IPSET: DVR-Test-v4 FWMark: 0xb000
Apr 23 14:36:31 domain_vpn_routing: Restore Policy - Adding IPTables rule for IPSET: DVR-Test-v4 Interface: wgc2 FWMark: 0xb000
Apr 23 14:36:31 domain_vpn_routing: Restore Policy - Added IPTables rule for IPSET: DVR-Test-v4 Interface: wgc2 FWMark: 0xb000
Apr 23 14:36:31 domain_vpn_routing: Restore Policy - Saving IPv4 IPSET for Test
Apr 23 14:36:31 domain_vpn_routing: Restore Policy - Save IPv4 IPSET for Test
Apr 23 14:36:31 domain_vpn_routing: Debug - DNS Director Interface: wgc2
Apr 23 14:36:31 domain_vpn_routing: Debug - Dig has been configured to use system DNS Server
Apr 23 14:36:31 domain_vpn_routing: Debug - Dig has been configured without DNS-over-TLS using system DNS Server
Apr 23 14:36:31 domain_vpn_routing: Query Policy - Adding CNAME: www.cnbc.com.edgekey.net to Test
Apr 23 14:36:31 domain_vpn_routing: Query Policy - Added CNAME: www.cnbc.com.edgekey.net to Test
Apr 23 14:36:31 domain_vpn_routing: Query Policy - Policy: Test Querying www.cnbc.com
Apr 23 14:36:31 domain_vpn_routing: Query Policy - Policy: Test Querying www.cnbc.com.edgekey.net
Apr 23 14:36:31 domain_vpn_routing: Query Policy - Updating Policy: Test
Apr 23 14:36:31 domain_vpn_routing: Query Policy - Updated Policy: Test
Apr 23 14:36:31 domain_vpn_routing: Debug - Routing Director Interface: wgc2
Apr 23 14:36:31 domain_vpn_routing: Debug - State: 1
Apr 23 14:36:31 domain_vpn_routing: Query Policy - Saving IPv6 IPSET for Test
Apr 23 14:36:31 domain_vpn_routing: Query Policy - Saved IPv6 IPSET for Test
Apr 23 14:36:31 domain_vpn_routing: Query Policy - Adding 23.64.175.204 to IPSET: DVR-Test-v4
Apr 23 14:36:31 domain_vpn_routing: Query Policy - Added 23.64.175.204 to IPSET: DVR-Test-v4
Apr 23 14:36:31 domain_vpn_routing: Query Policy - Saving IPv4 IPSET for Test
Apr 23 14:36:31 domain_vpn_routing: Query Policy - Save IPv4 IPSET for Test
Apr 23 14:36:31 domain_vpn_routing: Query Policy - Processing Time: 0 seconds
Apr 23 14:36:31 domain_vpn_routing: Debug - Checking for Lock File: /var/lock/domain_vpn_routing.lock
Apr 23 14:36:31 domain_vpn_routing: Cleanup - Deleting /var/lock/domain_vpn_routing.lock
Apr 23 14:36:31 domain_vpn_routing: Cleanup - Deleted /var/lock/domain_vpn_routing.lock

**Comment by Jerkysan** [comment]
create DVR-Test-v4 hash:ip family inet hashsize 1024 maxelem 65536 comment
add DVR-Test-v4 23.64.175.204 comment "www.cnbc.com,www.cnbc.com.edgekey.net"
~
~
~
~
Is in the file

**Comment by Jerkysan** [comment]
Ok something is just wrong with using CNBC as a test. It worked with two other sites I added.

**Comment by Ranger802004** [comment]
It looks like it picked up a CNAME record and and then an IP record from the CNAME record.

**Comment by Jerkysan** [comment]
Thanks a lot for resolving this.. Really appreciate how fast you did.

**Comment by Jerkysan** [comment]
Thank you for fixing it!
