### ISSUE TITLE
Feature request: policy to interface routing info

### ISSUE THREAD

**Issue by dorner365** [Ranger802004/asusmerlin#80]
Would you consider adding a 4th item under Information that shows the ipset -> interface routing map, i.e.:
1. DVR-aaa-v4 -> wgc2
2. DVR-bbb-v4 -> ovpnc1
3. ...?

**Comment by Ranger802004** [comment]
This is show in show policies view showing which interface is applied to the policy.  Technically the IPSet isn't mapped to an interface.  It is created to apply the FWMark to traffic destined to the IP addresses in it.  The IP rules created are what route the designated traffic by FWMark to the correct interface.

**Comment by dorner365** [comment]
Yes, leaving technicalities aside, it is shown for _each_ ipset, independently. When you have several ipsets and using several interfaces an overall map in one screen is what I'm talking about as above. The user friendly version of `iptables -nvL PREROUTING -t mangle --line` as above.

**Comment by Ranger802004** [comment]
Wouldn't it make more logical sense to have the policy summary view show the interfaces for each? The IPsets are just essentially the policy names with a prefix and suffix in them.

**Comment by dorner365** [comment]
Yes, that's the spirit. Thanks!

**Comment by Ranger802004** [comment]
Here is a preview:

<img width="804" alt="Image" src="https://github.com/user-attachments/assets/87c6608c-8597-454d-9670-c1d8318780c6" />

**Comment by dorner365** [comment]
Very good! I just realize now that the reason for the request was to know if one (more) of the interfaces is down. So 'status' -'connected' or 'stopped' would complete ethe picture.

**Comment by Ranger802004** [comment]
How about this?

<img width="437" alt="Image" src="https://github.com/user-attachments/assets/9243a6cc-a66d-4da5-afdb-a299145853e9" />

**Comment by Ranger802004** [comment]
This is now available in v3.2.0-beta1 on the beta channel.

Release Notes:
Enhancements:
- Added custom priority settings for interfaces that can be modified using the configuration menu.
- Enhance Query ASN logic to handle larger ASNs and optimize query time. This requires grep to be installed from Entware.
- Querying policies now can use grep from Entware to efficiently process new IP addresses.
- Enhanced interface state detection logic.
- Showing policies now displays the associated interfaces and the connected state status.
- Minor optimization and performance enhancements.

Fixes:
- Querying policies will now properly delete temporary files generated under /tmp.
- Fixed UI bugs not allowing return in certain menus.
- Fixed configuration menu bug that was not showing Dual WAN DNS Settings when router was configured for Dual WAN.

**Comment by dorner365** [comment]
Here's an error:

![Image](https://github.com/user-attachments/assets/bbc590b8-b489-4599-82c3-b5100ee64742)

Also, note that wgc5 is connected and working. There is a total of 10 policies.

**Comment by dorner365** [comment]
I have no ASNs configured.

**Comment by dan-gill** [comment]
> I have no ASNs configured.

Sorry for the confusion; this was a request to add the same functionality when listing ASNs.

**Comment by dorner365** [comment]
The Wireguard interface detection still not working:

![Image](https://github.com/user-attachments/assets/0b4ff386-5959-41f3-bfcd-c4e14be5c1f9)

wgc2 and wgc5 are fully functional (selective routing works). Also, it would be a nice touch to allow exiting option 2 without CTRL-C. ovpnc4 is indeed disconnected.

**Comment by Ranger802004** [comment]
That is the state they are detected as for WireGuard when reading the system files.

**Comment by zinogo** [comment]
According to my experience "/etc/wg/wgcx.log" file will not be automatically generated. (Need view VPN WebUI to update wgcx.log)

Maybe execute “wg show wgcx > /etc/wg/wgcx.log" before following code to solve wg client interface detection issue.

IFNAME="$(awk '$1 == "interface:" {print $2}' /etc/wg/wgcx.log 2>/dev/null)"

**Comment by zinogo** [comment]
> > According to my experience "/etc/wg/wgcx.log" file will not be automatically generated. (Need view VPN WebUI to update wgcx.log)
> > Maybe execute “wg show wgcx > /etc/wg/wgcx.log" before following code to solve wg client interface detection issue.
> > IFNAME="$(awk '$1 == "interface:" {print $2}' /etc/wg/wgcx.log 2>/dev/null)"
> 
> That seems to align with what I described here: [#83 (comment)](https://github.com/Ranger802004/asusmerlin/issues/83#issuecomment-2876567750)

I add following command to "/jffs/scripts/firewall-start" file for workaround. Working good  in  v3.1.1.

wg show wgc1 > /etc/wg/wgc1.log
(1 can replace to your wg number)

**Comment by dan-gill** [comment]
> I add following command to "/jffs/scripts/firewall-start" file for workaround. Working good in v3.1.1.
> 
> wg show wgc1 > /etc/wg/wgc1.log (1 can replace to your wg number)

Thanks! I added this to firewall-start so that it will work with all connected WireGuard clients:
```bash
# Refresh WireGuard interface logs for domain_vpn_routing
for IF in $(ip link show | awk -F: '/wgc[0-9]+:/{print $2}' | tr -d ' '); do
  wg show "$IF" > "/etc/wg/${IF}.log"
done
```

**Comment by dan-gill** [comment]
Since you already maintain a mapping between policy, ASN, and interface, would it make sense to add a `queryinterface $1` option?

This would allow `wgclient-start` to query only the policies tied to the active interface, instead of calling `querypolicy all`. It would improve clarity and performance, especially on multi-VPN setups, and avoid unnecessary evaluations when only a single interface comes up.

For context, `wgclient-start` currently ends with:
```sh
sh /jffs/scripts/domain_vpn_routing.sh querypolicy all # domain_vpn_routing_queryall
```

A targeted alternative like:
```sh
sh /jffs/scripts/domain_vpn_routing.sh queryinterface "$1"
```
...would make the logic more efficient and interface-aware.

**Comment by Ranger802004** [comment]
> Since you already maintain a mapping between policy, ASN, and interface, would it make sense to add a `queryinterface $1` option?
> 
> This would allow `wgclient-start` to query only the policies tied to the active interface, instead of calling `querypolicy all`. It would improve clarity and performance, especially on multi-VPN setups, and avoid unnecessary evaluations when only a single interface comes up.
> 
> For context, `wgclient-start` currently ends with:
> 
> sh /jffs/scripts/domain_vpn_routing.sh querypolicy all # domain_vpn_routing_queryall
> A targeted alternative like:
> 
> sh /jffs/scripts/domain_vpn_routing.sh queryinterface "$1"
> ...would make the logic more efficient and interface-aware.
> 
> Something similar could also be added to `openvpn-event`, using the tunnel interface name passed to that script.

Negative, this will cause more issues then it helps considering when you have multiple interfaces starting the first iteration would lock the script execution and not allow the rest to run (this is done for integrity reasons).  querypolicy all will not run more than once so there is no "efficiency" to gain by this, the extra iterations called will simply be rejected while it's locked.  Also the initial load will check if existing policies need to be restored first as this can be needed for a firewall restart, interface restart, etc.  For the best consistency in functionality the existing way was chosen.

**Comment by Ranger802004** [comment]
> > > According to my experience "/etc/wg/wgcx.log" file will not be automatically generated. (Need view VPN WebUI to update wgcx.log)
> > > Maybe execute “wg show wgcx > /etc/wg/wgcx.log" before following code to solve wg client interface detection issue.
> > > IFNAME="$(awk '$1 == "interface:" {print $2}' /etc/wg/wgcx.log 2>/dev/null)"
> > 
> > 
> > That seems to align with what I described here: [#83 (comment)](https://github.com/Ranger802004/asusmerlin/issues/83#issuecomment-2876567750)
> 
> I add following command to "/jffs/scripts/firewall-start" file for workaround. Working good in v3.1.1.
> 
> wg show wgc1 > /etc/wg/wgc1.log (1 can replace to your wg number)

This won't be necessary going forward, I am updating the interface detection logic for WireGuard interfaces that will have multiple methods of detecting the interface.  See below logic.  The log check will only be 1 detection method out of the 5.

```
  if [[ -n "$(ifconfig ${INTERFACE} | grep -o "${INTERFACE}")" ]] &>/dev/null || [[ -d "/proc/sys/net/ipv4/conf/${INTERFACE}" ]] &>/dev/null || [[ "${INTERFACE}" == "$(/usr/sbin/wg show ${INTERFACE} 2>/dev/null | grep -oE "interface:\s*\S*" | awk '{print $2}')" ]] &>/dev/null;then
    IFNAME="${INTERFACE}"
  elif [[ -n "$(awk '$1 == "interface:" {print $2}' /etc/wg/${INTERFACE}.log 2>/dev/null)" ]] &>/dev/null;then
    IFNAME="$(awk '$1 == "interface:" {print $2}' /etc/wg/${INTERFACE}.log 2>/dev/null)"
  elif [[ -n "$(nvram get ${INTERFACE}_addr & nvramcheck)" ]] &>/dev/null || [[ -s "/etc/wg/${INTERFACE}_status" ]] &>/dev/null;then
    ipaddr=""
    while [[ -z "${ipaddr}" ]] &>/dev/null;do
      ipaddr="$(nvram get ${INTERFACE}_addr)"
	done
	IFNAME="$(${ipbinpath}ip -br addr show to ${ipaddr} | awk '{print $1}')"
	unset ipaddr
  fi  
```

**Comment by Ranger802004** [comment]
> That last update solves it quite elegantly - thank you!
> 
> ![Image](https://github.com/user-attachments/assets/3d12db52-ddcd-4a7b-8594-57fb4419a0d0)
> 
> NOTE: ovpnc4 is currently on purpose disconnected.

Can you tell me why the last 2 are offset in the UI from the others? What is the length of the policy names you are using?

**Comment by Ranger802004** [comment]
Are these older policies? The script doesn't allow policies over 24 characters now so I accounted for that length.

**Comment by Ranger802004** [comment]
Ah the digits, I got it now.  I will clean that up for final release.

**Comment by dan-gill** [comment]
> Ah the digits, I got it now. I will clean that up for final release.

It also happens with ASNs, just an FYI since it clearly doesn't matter functionally.

![Image](https://github.com/user-attachments/assets/ca936c4c-10cc-464f-9959-b85d30ccb807)

**Comment by Ranger802004** [comment]
v3.2.0 has been released to the production channel

Release Notes:
Enhancements:
- Interface selection when creating or editing policies or adding ASNs will now allow easier selection by number list instead of manually typing the interface name.
- Enhanced deteection of WireGuard interface information.
- Added custom priority settings for interfaces that can be modified using the configuration menu.
- Enhance Query ASN logic to handle larger ASNs and optimize query time.  This requires grep to be installed from Entware.
- Querying policies now can use grep from Entware to efficiently process new IP addresses.
- Enhanced interface state detection logic.
- Showing policies now displays the associated interfaces and the connected state status.
- Showing ASNs now displays the associated interfaces and the connected state status.
- Minor optimization and performance enhancements.

Fixes:
- Querying policies will now properly delete temporary files generated under /tmp.
- Fixed UI bugs not allowing return in certain menus.
- Fixed configuration menu bug that was not showing Dual WAN DNS Settings when router was configured for Dual WAN.
- Minor bug fixes
